# 07-00_install_dependencies

# If packages have been deleted from gscratch/scrubbed, run the following lines:
# cmdstanr and rstan both apparently require some additional dependencies, try this:
install.packages("checkmate")
install.packages("data.table")
install.packages("jsonlite")
install.packages("processx")
install.packages("R6")
install.packages("withr")
install.packages("rlang")
install.packages("backports")
install.packages("abind")
install.packages("distributional")
install.packages("vctrs")
install.packages("generics")
install.packages("tidyverse")
install.packages("lifecycle")
install.packages("tibble")
install.packages("magrittr")
install.packages("ggplot2", dependcies = TRUE)
install.packages("gtable")
install.packages("dplyr")
install.packages("tidyselect")
install.packages("rprojroot")
install.packages("scales")
install.packages("munsell")
install.packages("colorspace")
install.packages("ggsignif")
install.packages("StanHeaders")
install.packages("inline")
install.packages("gridExtra")
install.packages("Rcpp")
install.packages("RcppParallel")
install.packages("loo")
install.packages("pkgbuild")
install.packages("QuickJSR")
install.packages("RcppEigen")
install.packages("BH")
install.packages("purrr")
install.packages("rstatix")
install.packages("broom")
install.packages("tidyr")
install.packages("car")
install.packages("carData")
install.packages("stringr")
install.packages("stringi")
install.packages("forcats")
install.packages("cowplot")
install.packages("labeling")
install.packages("farver")
install.packages("reshape2")
install.packages("plyr")
install.packages("ggthemes")
install.packages("timechange")
install.packages("lubridate")
# # install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")), dependencies = TRUE)
# # alternatively: remotes::install_github("stan-dev/cmdstanr")
# alternatively: renv::install("stan-dev/cmdstanr") # this ended up working
install.packages("renv")
renv::install("stan-dev/cmdstanr")
install.packages("rstan", repos = c('https://stan-dev.r-universe.dev', getOption("repos")))
install.packages("bayesplot")
install.packages("here")
install.packages("ggpubr")
install.packages("Formula")
install.packages("htmltools")
install.packages("digest")
install.packages("fastmap")
install.packages("miniUI")
install.packages("httpuv")
install.packages("shiny")
install.packages("later")
install.packages("xtable")
install.packages("promises")
install.packages("ggExtra")
install.packages("mime")
install.packages("patchwork")
